"""
Autonomous Conversational Stylist for StylistAI
Natural, intelligent conversations for styling recommendations with autonomous tool usage
"""

from typing import Dict, Optional, List, TypedDict, Annotated
from operator import add
import logging
from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
from app.config import settings
from app.services.weather_service import WeatherService

logger = logging.getLogger(__name__)


# Define conversation state
class ConversationState(TypedDict):
    """State for styling conversation"""
    messages: Annotated[List[BaseMessage], add]
    user_id: str
    user_preferences: Optional[dict]


# Define tools for the conversational agent
@tool
def get_weather_info(location: str, date: str = "today") -> dict:
    """
    Get weather information for a specific location and date.

    Use this tool when:
    - User mentions a location (city, place, area)
    - You need weather to make appropriate outfit recommendations
    - User asks about weather

    Args:
        location: City or location name (e.g., "New York", "Miami", "Seattle")
        date: When they need weather (e.g., "today", "tomorrow", "this weekend")

    Returns:
        Weather information including temperature, conditions, and styling advice
    """
    try:
        logger.info(f"[Weather Tool] Fetching weather for {location} on {date}")
        weather = WeatherService.get_weather_for_location_and_date(location, date)

        if not weather:
            return {
                "error": f"Could not fetch weather for {location}",
                "suggestion": "Proceeding with general recommendations"
            }

        return {
            "location": location,
            "date": date,
            "temperature": weather.get("temperature", "Unknown"),
            "conditions": weather.get("conditions", "Unknown"),
            "description": weather.get("description", ""),
            "feels_like": weather.get("feels_like", ""),
            "humidity": weather.get("humidity", ""),
            "styling_advice": weather.get("styling_advice", "")
        }
    except Exception as e:
        logger.error(f"Error fetching weather: {e}")
        return {
            "error": str(e),
            "suggestion": "Recommend versatile layering options"
        }


# REMOVED: generate_outfit_recommendations tool
# Using Pure Sequential Pattern: API orchestrates Agent 2 → Agent 3 explicitly
# Agent 2 (this conversational agent) only gathers context
# Agent 3 (langgraph) is called by API when context is complete

# Create LLM with tools bound
def create_conversational_llm():
    """Create LLM with styling conversation tools bound"""
    llm = ChatOpenAI(
        model=settings.OPENAI_LLM_MODEL,
        api_key=settings.OPENAI_API_KEY,
        temperature=0.8  # Higher temperature for natural, warm conversation
    )

    # PURE SEQUENTIAL PATTERN: Only weather tool
    # Recommendations are generated by API orchestration (not via tool)
    tools = [get_weather_info]
    return llm.bind_tools(tools)


# Agent node - autonomous conversation
async def conversational_agent_node(state: ConversationState) -> ConversationState:
    """
    Autonomous conversational stylist that naturally chats and decides when to use tools
    """
    logger.info(f"[Conversational Agent] Processing for user: {state['user_id']}")

    # Get user preferences
    user_prefs = state.get('user_preferences', {})
    default_location = user_prefs.get('default_location', '') if user_prefs else ''
    style_aesthetics = user_prefs.get('style_aesthetics', []) if user_prefs else []
    colors = user_prefs.get('colors', []) if user_prefs else []
    occasions = user_prefs.get('occasions', []) if user_prefs else []

    # Build system message
    system_message = SystemMessage(content=f"""You are Nikhil, a friendly and knowledgeable personal stylist AI assistant for StylistAI.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 YOUR ROLE:

Have natural, friendly conversations to help users with styling advice. You're like chatting with a stylish friend over coffee, NOT a formal consultation!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👤 USER PROFILE (from onboarding):

{f"- Default Location: {default_location}" if default_location else "- No default location set"}
{f"- Style Aesthetics: {', '.join(style_aesthetics)}" if style_aesthetics else ""}
{f"- Favorite Colors: {', '.join(colors)}" if colors else ""}
{f"- Typical Occasions: {', '.join(occasions)}" if occasions else ""}

Use this profile to personalize recommendations, but still gather event-specific context!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🛠️ YOUR TOOL (use intelligently):

**get_weather_info(location, date)**
- Get weather for outfit planning
- Call when user mentions location OR use default_location
- Essential for weather-appropriate recommendations

NOTE: You DON'T generate recommendations directly!
- Your job: Gather context through conversation (occasion, formality, when, where)
- Once you have complete context, simply indicate you're ready
- The API will call the recommendations engine automatically

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 CONTEXT TO GATHER (before recommendations can be generated):

**MANDATORY:**
1. **Occasion** - What's the event? (date, meeting, wedding, casual, etc.)
2. **Formality** - How dressed up? (casual, business casual, formal, etc.)
3. **When** - Today, tomorrow, next week? (for weather)
4. **Where** - Location (for weather) - use default_location if not mentioned
5. **Weather** - Call get_weather_info tool to fetch weather data

**NICE TO HAVE:**
6. **Activity level** - Sitting, walking, dancing?
7. **Duration** - Quick meeting or all-day event?
8. **Time of day** - Morning, afternoon, evening?
9. **Special requirements** - Dress code, comfort needs?

**YOUR ROLE:** Gather this context naturally through conversation, then indicate readiness!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💬 CONVERSATION STYLE:

✅ **DO:**
- Be warm, enthusiastic, and supportive
- Use emojis occasionally (not excessively)
- Ask follow-up questions naturally
- Show genuine interest in their plans
- Give quick styling tips during conversation
- Reference their profile (style, colors, location)
- Acknowledge their answers warmly before asking next question

❌ **DON'T:**
- Don't immediately jump to recommendations
- Don't ask multiple questions at once (max 1-2)
- Don't be overly formal or robotic
- Don't give full outfit recommendations until you have enough context

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎬 CONVERSATION FLOW EXAMPLES:

**Example 1: Simple Request**

User: "What should I wear for a date?"

You: "Ooh, a date! Exciting! 😊 When is it - tonight, this weekend, or coming up soon?"

User: "Tomorrow evening"

You: "Where will you be for your date?"

User: "Downtown Seattle"

You: [Calls get_weather_info("Seattle", "tomorrow")]
[Weather result received]

You: "Perfect! Tomorrow evening in Seattle will be 65°F and partly cloudy.
     What's the vibe - casual coffee, nice dinner, or something else?"

User: "Nice dinner"

You: [Has complete context: date + tomorrow evening + Seattle + weather + nice dinner]
[Uses readiness phrase that API will detect]

You: "Perfect! Let me find you the ideal outfit for your nice dinner date tomorrow evening! 💫"

[API detects THREE signals:]
[✅ has_weather = True]
[✅ agent_signals_ready = True ("let me find" detected)]
[✅ min_conversation_depth = True (multiple exchanges)]
[→ Context complete! API calls LangGraph agent]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Example 2: Vague Request**

User: "I need outfit help"

You: "I'd love to help! What's the occasion? Is it for work, a special event,
     or just everyday styling?"

User: "Work"

You: "Got it! What's your work environment like - business formal, business casual,
     or more relaxed?"

User: "Business casual"

You: "Perfect! When do you need this outfit?"

User: "For tomorrow"

You: [Calls get_weather_info(default_location, "tomorrow") - using profile location]
[Has complete context: work + business casual + tomorrow + weather]

You: "Great! Let me find you the perfect business casual outfit for tomorrow!"

[API detects: weather ✅ + "let me find" ✅ + conversation depth ✅ → Orchestrates recommendations]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Example 3: User Volunteers Full Context**

User: "I have a business meeting tomorrow afternoon in NYC, business casual dress code"

You: [Amazing! They gave everything: occasion, when, where, formality!]
[Calls get_weather_info("New York", "tomorrow")]
[Weather result received]
[Context is complete!]

You: "Perfect! Let me find you the ideal outfit for your business casual meeting tomorrow in NYC! 💼"

[API detects THREE signals and orchestrates recommendations]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Example 4: Just Chatting (No Immediate Recommendations)**

User: "Hey, what's trending in fashion?"

You: "Hey! Great question! 🌟 Right now, we're seeing a lot of:
     - Oversized tailoring (blazers, coats)
     - Monochromatic looks
     - Sustainable fashion choices
     - '90s minimalism comeback

     Are you thinking about updating your wardrobe, or just curious?"

[No recommendations needed - they're just browsing!]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 WHEN TO CALL TOOL:

**get_weather_info:**
✅ Call when location mentioned OR use default_location
✅ Call once you know the occasion/event and when it is
❌ Don't call if user is just browsing/chatting
❌ Don't call multiple times (cache the weather data)

**Indicating Readiness for Recommendations:**
✅ When you have: occasion + formality + weather + location + when
✅ Use SPECIFIC readiness phrases (API detects these):
   - "Let me find you the perfect outfit!"
   - "Perfect! Let me get some great options for you!"
   - "Great! Let me put together some recommendations!"
   - "I've got all the details I need!"
   - "I'll find you some amazing outfits!"
✅ Be enthusiastic and signal you're ready to help
✅ API detects these phrases + weather data + conversation depth
❌ Never say "I'll call the recommendations tool" (internal API logic)
❌ Don't use generic phrases like "sounds good" (won't trigger detection)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🚫 HANDLING OFF-TOPIC:

You are a PERSONAL STYLIST AI - your expertise is fashion, styling, outfits, and wardrobe advice ONLY.

If user asks unrelated questions (politics, sports, math, cooking):
- Politely acknowledge but redirect to styling
- Stay in character

Example:
User: "What's the capital of France?"
You: "Haha, that's outside my expertise! I'm all about fashion. 😊
     But speaking of France - Parisian style is so chic!
     Need help with any outfits?"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

REMEMBER:
- Be conversational and fun!
- Gather context through natural dialogue (3-5 messages usually)
- Use tools intelligently (not every conversation needs recommendations)
- Reference their profile to personalize
- Make users feel comfortable and excited about fashion!
""")

    # Build messages
    messages = [system_message]
    messages.extend(state['messages'])

    # Get LLM with tools
    llm_with_tools = create_conversational_llm()

    # Invoke LLM
    response = await llm_with_tools.ainvoke(messages)

    logger.info(f"[Conversational Agent] LLM response type: {type(response)}")
    if hasattr(response, 'tool_calls') and response.tool_calls:
        logger.info(f"[Conversational Agent] LLM called {len(response.tool_calls)} tools: {[tc.get('name') for tc in response.tool_calls]}")

    return {"messages": [response]}


# Tool execution node - PURE SEQUENTIAL PATTERN
tools_list = [get_weather_info]  # Only weather tool, recommendations via API orchestration
tool_node = ToolNode(tools_list)


# Router: decide if we should continue to tools or end
def should_continue(state: ConversationState) -> str:
    """Determine if we should call tools or end"""
    messages = state['messages']
    last_message = messages[-1]

    # If LLM makes tool calls, route to tools node
    if hasattr(last_message, 'tool_calls') and last_message.tool_calls:
        logger.info(f"[Conversational Router] Routing to tools")
        return "tools"

    # Otherwise, done with this turn
    logger.info(f"[Conversational Router] Ending turn")
    return "end"


# Build the LangGraph workflow
def create_conversational_stylist_agent() -> StateGraph:
    """Create and compile the autonomous conversational stylist"""

    workflow = StateGraph(ConversationState)

    # Add nodes
    workflow.add_node("agent", conversational_agent_node)
    workflow.add_node("tools", tool_node)

    # Set entry point
    workflow.set_entry_point("agent")

    # Add conditional edges
    workflow.add_conditional_edges(
        "agent",
        should_continue,
        {
            "tools": "tools",
            "end": END
        }
    )

    # After tools, go back to agent for final response
    workflow.add_edge("tools", "agent")

    return workflow.compile()


# Main execution function
async def chat_with_stylist(
    user_id: str,
    user_message: str,
    conversation_history: Optional[List[dict]] = None,
    user_preferences: Optional[dict] = None
) -> dict:
    """
    Have a conversation with the autonomous stylist

    Args:
        user_id: User's ID
        user_message: User's latest message
        conversation_history: Previous messages in conversation
        user_preferences: User's profile from onboarding

    Returns:
        Agent's response and metadata
    """

    agent = create_conversational_stylist_agent()

    # Build messages from history
    messages = []
    if conversation_history:
        for msg in conversation_history[-10:]:  # Keep last 10 messages for context
            if msg.get("role") == "user":
                messages.append(HumanMessage(content=msg["content"]))
            elif msg.get("role") == "assistant":
                messages.append(AIMessage(content=msg["content"]))

    # Add current user message
    messages.append(HumanMessage(content=user_message))

    # Initial state
    initial_state: ConversationState = {
        "messages": messages,
        "user_id": user_id,
        "user_preferences": user_preferences
    }

    logger.info(f"\n{'='*50}")
    logger.info(f"Conversational Stylist - User: {user_id}")
    logger.info(f"Message: {user_message}")
    logger.info(f"{'='*50}\n")

    # Run agent
    final_state = await agent.ainvoke(initial_state)

    # Extract response
    final_messages = final_state['messages']

    # Get last AI message (skip tool messages and system messages)
    ai_response = None
    for msg in reversed(final_messages):
        if isinstance(msg, AIMessage) and hasattr(msg, 'content') and msg.content:
            # Make sure it's not a tool call message
            if not (hasattr(msg, 'tool_calls') and msg.tool_calls):
                ai_response = msg.content
                break

    # Check what tools were used - PURE SEQUENTIAL PATTERN
    tools_used = []
    weather_info = None

    for msg in final_messages:
        if isinstance(msg, ToolMessage):
            # Track which tool was called
            tool_name = msg.name if hasattr(msg, 'name') else 'unknown'
            tools_used.append(tool_name)

            # Extract data from tool results
            try:
                if isinstance(msg.content, str):
                    result = eval(msg.content)  # Tool results are string representations
                else:
                    result = msg.content

                # ONLY weather tool exists in pure sequential pattern
                if tool_name == 'get_weather_info' and not result.get('error'):
                    weather_info = result

            except Exception as e:
                logger.error(f"Error parsing tool result: {e}")

    # Determine if more context is needed - MULTI-SIGNAL DETECTION
    # More robust than just checking weather!

    # Signal 1: Weather has been fetched
    has_weather = weather_info is not None

    # Signal 2: Agent indicates readiness through response language
    # Look for phrases that indicate agent is ready to find outfits
    readiness_phrases = [
        "let me find",
        "i'll find",
        "let me get",
        "i've got all",
        "i have all",
        "perfect! let me",
        "great! let me",
        "i can help you with that",
        "here's what i suggest",
        "let me put together",
        "i'll put together"
    ]
    agent_signals_ready = any(
        phrase in ai_response.lower()
        for phrase in readiness_phrases
    ) if ai_response else False

    # Signal 3: Minimum conversation depth (at least 1-2 exchanges)
    # Prevents weather-only queries from triggering recommendations
    min_conversation_depth = len(conversation_history) >= 2  # At least 1 user msg + 1 assistant msg before this

    # Context is complete when:
    # 1. Weather fetched (indicates location + when)
    # 2. Agent signals readiness in response
    # 3. Had at least minimal conversation (not just "what's the weather?")
    needs_more_context = not (has_weather and agent_signals_ready and min_conversation_depth)

    logger.info(f"[Context Detection] has_weather={has_weather}, agent_ready={agent_signals_ready}, min_depth={min_conversation_depth}")
    logger.info(f"[Context Detection] needs_more_context={needs_more_context}")

    # PURE SEQUENTIAL: No recommendations here!
    # API will call langgraph agent when context is complete
    return {
        "response": ai_response or "I'm here to help you look great! What can I help you with?",
        "recommendations": [],  # Always empty - API orchestrates recommendations
        "weather_info": weather_info,
        "tools_used": tools_used,
        "has_recommendations": False,  # Always False - recommendations come from API
        "needs_more_context": needs_more_context,  # Multi-signal detection
        "context_signals": {  # Debug info for UI/logging
            "has_weather": has_weather,
            "agent_signals_ready": agent_signals_ready,
            "min_conversation_depth": min_conversation_depth
        }
    }


# Singleton instance
_conversational_stylist = None


def get_autonomous_conversational_stylist():
    """Get or create conversational stylist instance"""
    global _conversational_stylist
    if _conversational_stylist is None:
        _conversational_stylist = True  # Placeholder
    return chat_with_stylist
